### ISSUE TITLE
Light is not rendered in basic-movement example

### ISSUE THREAD

**Issue by kanduvisla** [unstoppablecarl/js-roguelike-skeleton#5]
In the basic movement example, the light should be rendered along with the zombie, but this isn't the case. Is this because of a missing renderer?

    game.renderer.layers = [
      new RL.RendererLayer(game, 'map', {draw: false, mergeWithPrevLayer: false}),
      new RL.RendererLayer(game, 'entity', {draw: false, mergeWithPrevLayer: true}),
      new RL.RendererLayer(game, 'lighting', {draw: true, mergeWithPrevLayer: false})
    ];

**Comment by unstoppablecarl** [comment]
Which example are you referring to?

Are you saying an example does not work correctly?

Or you made changes to an example and it is not behaving as expected?

**Comment by kanduvisla** [comment]
This example: http://unstoppablecarl.github.io/js-roguelike-skeleton/manual/index/entity/basic-movement.html

The light is not following the zombie (tested in Chrome). If I add the lighting layer it works. Don't know if this is a mistake in the example or if I'm missing something.

**Comment by unstoppablecarl** [comment]
Yes, the lighting layer was missing I pushed a fix. Thanks.
